---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/workload: magnolia-author-frontend
  labels:
    k8s.kuboard.cn/name: magnolia-author-frontend
  name: magnolia-author-frontend
  namespace: zb-schools
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: magnolia-author-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-06-26T14:15:57+08:00"
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: magnolia-author-frontend
    spec:
      containers:
        - image: "767397694429.dkr.ecr.ap-southeast-1.amazonaws.com/sph/magnolia-author-frontend"
          imagePullPolicy: Always
          name: magnolia-author-frontend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 50
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 2
          resources:
            limits:
              cpu: "1"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: confd
              subPath: default.conf
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: default.conf
                path: default.conf
            name: author-nginx-conf
          name: confd
---
apiVersion: v1
data:
  default.conf: |-
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

         location / {
            root /usr/share/nginx/html;
            index  index.html;
            client_max_body_size 1000m;
            try_files $uri $uri/ /authorFrontend/index.html @rewrites;
        }

        location @rewrites { 
                rewrite ^(.+)$ /index.html break;  
            }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }
kind: ConfigMap
metadata:
  name: author-nginx-conf
  namespace: zb-schools
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-frontend-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    k8s.kuboard.cn/name: magnolia-author-frontend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
