---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/workload: magnolia-public-frontend
  labels:
    k8s.kuboard.cn/name: magnolia-public-frontend
  name: magnolia-public-frontend
  namespace: zb-schools
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: magnolia-public-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-06-26T13:53:43+08:00"
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: magnolia-public-frontend
    spec:
      containers:
        - image: "767397694429.dkr.ecr.ap-southeast-1.amazonaws.com/sph/magnolia-public-frontend"
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1.2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi 
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: volume-2hfc3
              subPath: default.conf
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: default.conf
                path: default.conf
            name: nginx2-conf
          name: volume-2hfc3
---
apiVersion: v1
data:
  default.conf: |-
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 3;
    gzip_proxied any;
    gzip_vary on;
    gzip_types
       application/atom+xml
       application/javascript
       application/json
       application/ld+json
       application/manifest+json
       application/rss+xml
       application/vnd.geo+json
       application/vnd.ms-fontobject
       application/x-font-ttf
       application/x-web-app-manifest+json
       application/xhtml+xml
       application/xml
       font/opentype
       image/bmp
       image/svg+xml
       image/x-icon
       text/cache-manifest
       text/css
       text/plain
       text/vcard
       text/vnd.rim.location.xloc
       text/vtt
       text/x-component
       text/x-cross-domain-policy;
    server {
            listen       80;
            listen  [::]:80;
            server_name  localhost;
            client_max_body_size 100M;

            location / {
                    root /usr/share/nginx/html;
                    index index.html;
                    expires -1;
                    client_max_body_size 1000m;
                    try_files $uri $uri/ /index.html @rewrites;

                    location ~* \.(js|css)$ {
                        expires 7d;
                        add_header Cache-Control "public, no-cache, max-age=604800";
                    }
                }

            location /lms/file/uploadFile {
                proxy_pass http://saas-homework-service-svc:8080/file/uploadFile;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /lms/teacherClass {
                proxy_pass http://saas-homework-service-svc:8080/teacherClass;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /lms/file/getRedirectUrl {
                  proxy_pass http://saas-homework-service-svc:8080/file/getRedirectUrl;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /lms/yd/textToSpeech {
                  proxy_pass http://saas-homework-service-svc:8080/yd/textToSpeech;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /lms/excel {
                  proxy_pass http://saas-homework-service-svc:8080/excel;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
            }


            
            location @rewrites {
                rewrite ^(.+)$ /index.html break;
            }
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
    }
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: nginx2-conf
  namespace: zb-schools
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-public-frontend-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    k8s.kuboard.cn/name: magnolia-public-frontend
