---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: author-s3-pv
spec:
  capacity:
    storage: 100Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: zb-schools # Namespace is required even though it's in "default" namespace.
    name: author-s3-pv # Name of your PVC
  mountOptions:
    - allow-delete
    - region ap-southeast-1
    - prefix author/
    - sse aws:kms # Use customer managed KMS key for server side encryption
    - sse-kms-key-id arn:aws:kms:ap-southeast-1:767397694429:key/c78efda0-5009-4e39-a1ff-7e92aa94e651 # set key id (optional)
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: s3-sph-zb-schools-dev-magnolia-share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: author-s3-pv
  namespace: zb-schools
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 100Gi # Ignored, required
  volumeName: author-s3-pv # Name of your PV
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/workload: magnolia-author-backend
  labels:
    k8s.kuboard.cn/name: magnolia-author-backend
  name: magnolia-author-backend
  namespace: zb-schools
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s.kuboard.cn/name: magnolia-author-backend
  podManagementPolicy: OrderedReady  
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-06-26T13:41:20+08:00"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sph-zb-schools-cms-vault-reader"
        vault.hashicorp.com/agent-inject-secret-db-config: "zb-schools/db/creds/zb-schools-db-role"
        vault.hashicorp.com/agent-inject-secret-kv-config: "zb-schools/kv/config"
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/namespace: "admin/engr/zb_schools/dev"
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: magnolia-author-backend
    spec:
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: author-s3-pv
      containers:
        - env:
            - name: TZ
              value: CST-8
            - name: BASE_URL
              value: "https://sit.zbschools.sg/authorFrontend"
            - name: ENV_TYPE
              value: "sit"
            - name: INSTANCE_TYPE
              value: "magnoliaAuthor"
          image: "767397694429.dkr.ecr.ap-southeast-1.amazonaws.com/sph/magnolia-author-backend"
          imagePullPolicy: IfNotPresent
          name: magolia-backend
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/local/tomcat/webapps/repositories/magnolia/share-data
          ports:
            - containerPort: 8080
              name: port8080
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 6Gi
            requests:
              cpu: "1"
              memory: 6Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: service-account-sph-zb-schools
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-backend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    k8s.kuboard.cn/name: magnolia-author-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-backend-svc-0
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: magnolia-author-backend-0
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-backend-svc-1
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: magnolia-author-backend-1 
  sessionAffinity: ClientIP
