---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/workload: magnolia-author-backend
  labels:
    k8s.kuboard.cn/name: magnolia-author-backend
  name: magnolia-author-backend
  namespace: zb-schools
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/name: magnolia-author-backend
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-06-26T13:41:20+08:00"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sph-zb-schools-cms-vault-reader"
        vault.hashicorp.com/agent-inject-secret-db-config: "zb-schools/db/creds/zb-schools-db-role"
        vault.hashicorp.com/agent-inject-secret-kv-config: "zb-schools/kv/config"
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/namespace: "admin/engr/zb_schools/dev"
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: magnolia-author-backend
    spec:
      containers:
        - env:
            - name: TZ
              value: CST-8
            - name: BASE_URL
              value: "https://sit.zbschools.sg/authorFrontend"
          image: "767397694429.dkr.ecr.ap-southeast-1.amazonaws.com/sph/magnolia-author-backend"
          imagePullPolicy: IfNotPresent
          name: magolia-backend
          ports:
            - containerPort: 8080
              name: port8080
              protocol: TCP
          resources:
            limits:
              cpu: "1.2"
              memory: 6Gi
            requests:
              cpu: "1"
              memory: 6Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: "/usr/local/tomcat/webapps/repositories_training-old"
              name: author-volume-old
            - mountPath: "/usr/local/tomcat/webapps/repositories_training"
              name: author-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: service-account-sph-zb-schools
      volumes:
        - name: author-volume-old
          persistentVolumeClaim:
            claimName: ebs-author-01
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: author-volume
        namespace: zb-schools
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ebs-sc
        volumeMode: Filesystem
      status:
        phase: Pending  
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-backend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    k8s.kuboard.cn/name: magnolia-author-backend
