---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public-1
  namespace: zb-schools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 5Gi