---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/workload: magnolia-author-backend
  labels:
    k8s.kuboard.cn/name: magnolia-author-backend
  name: magnolia-author-backend
  namespace: zb-schools
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s.kuboard.cn/name: magnolia-author-backend
  podManagementPolicy: OrderedReady  
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-06-26T13:41:20+08:00"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sph-zb-schools-cms-vault-reader"
        vault.hashicorp.com/agent-inject-secret-db-config: "zb-schools/db/creds/zb-schools-db-role"
        vault.hashicorp.com/agent-inject-secret-kv-config: "zb-schools/kv/config"
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/namespace: "admin/engr/zb_schools/prd"
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: magnolia-author-backend
    spec:
      containers:
        - env:
            - name: TZ
              value: CST-8
            - name: BASE_URL
              value: "https://prd.zbschools.sg/authorFrontend"
            - name: ENV_TYPE
              value: "prd"
            - name: INSTANCE_TYPE
              value: "magnoliaAuthor"
          image: "905418451605.dkr.ecr.ap-southeast-1.amazonaws.com/sph/magnolia-author-backend"
          imagePullPolicy: IfNotPresent
          name: magolia-backend
          ports:
            - containerPort: 8080
              name: port8080
              protocol: TCP
          resources:
            limits:
              cpu: "6"
              memory: 12Gi
            requests:
              cpu: "6"
              memory: 12Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: service-account-sph-zb-schools
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-backend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    k8s.kuboard.cn/name: magnolia-author-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-backend-svc-0
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: magnolia-author-backend-0
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: zb-schools
  name: magnolia-author-backend-svc-1
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: magnolia-author-backend-1 
  sessionAffinity: ClientIP
