---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-transfer-service
  namespace: zb-schools
  labels:
    k8s.kuboard.cn/name: saas-transfer-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/name: saas-transfer-service
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-09-25T11:46:16+08:00"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sph-zb-schools-cms-vault-reader"
        vault.hashicorp.com/agent-inject-secret-db-config: "zb-schools/db/creds/zb-schools-db-role"
        vault.hashicorp.com/agent-inject-secret-kv-config: "zb-schools/kv/config"
        vault.hashicorp.com/agent-inject-secret-aksk-config: "zb-schools/kv/aksk"
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/namespace: "admin/engr/zb_schools/prd"
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: saas-transfer-service
    spec:
      containers:
        - command:
            - /bin/bash
            - "-ce"
            - java  -Xms2048m -Xmx2048m -jar /opt/app/saas-transfer-service.jar
          env:
            - name: TZ
              value: CST-8
            - name: RUN_ENV
              value: "prd"
          image: "905418451605.dkr.ecr.ap-southeast-1.amazonaws.com/sph/saas-transfer-service"
          imagePullPolicy: IfNotPresent
          name: transfer
          ports:
            - containerPort: 8081
              name: port8081
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 6Gi
            requests:
              cpu: "2"
              memory: 6Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: service-account-sph-zb-schools
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: saas-transfer-service
  name: saas-transfer-service-svc
  namespace: zb-schools
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    k8s.kuboard.cn/name: saas-transfer-service
  sessionAffinity: None
  type: ClusterIP
