---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    k8s.kuboard.cn/workload: magnolia-public-backend
  labels:
    k8s.kuboard.cn/name: magnolia-public-backend
  name: magnolia-public-backend
  namespace: zb-schools
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: magnolia-public-backend
  serviceName: ''
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2024-06-25T17:16:12+08:00'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-db-config: zb-schools/db/creds/zb-schools-db-role
        vault.hashicorp.com/agent-inject-secret-kv-config: zb-schools/kv/config
        vault.hashicorp.com/log-level: debug
        vault.hashicorp.com/namespace: admin/engr/zb_schools/qa
        vault.hashicorp.com/role: sph-zb-schools-cms-vault-reader
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: magnolia-public-backend
    spec:
      containers:
        - env:
            - name: TZ
              value: CST-8
            - name: BASE_URL
              value: 'https://uat.zbschools.sg'
          image: >-
            975050283759.dkr.ecr.ap-southeast-1.amazonaws.com/sph/magnolia-public-backend
          imagePullPolicy: Always
          name: magolia-public
          ports:
            - containerPort: 8080
              name: port8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/tomcat/webapps/repositories_training
              name: public-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: service-account-sph-zb-schools
      serviceAccountName: service-account-sph-zb-schools
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: public-volume
        namespace: zb-schools
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ebs-sc
        volumeMode: Filesystem
      status:
        phase: Pending
